#!/usr/bin/env python3
import html,json
from pathlib import Path
from urllib.parse import quote
ROOT=Path(__file__).resolve().parents[1]
BASE="https://developiig-hue.github.io/IIG_PLATFORM_DEMO/"
news=json.loads((ROOT/"content/public-news.json").read_text(encoding="utf-8"))["items"]
advice=json.loads((ROOT/"content/public-advice.json").read_text(encoding="utf-8"))["items"]
news=[x for x in news if x.get("status")=="APPROVED" and x.get("admin_approved") is True]
def t(x): return x.get("title",{}).get("ua","")
def link(kind,slug): return BASE+("article.html" if kind=="news" else "advice-article.html")+"?id="+quote(slug)
def esc(x): return html.escape(str(x))
news_cards="".join(f'<a class="news-card" href="{link("news",x["slug"])}"><span class="sector">{esc(x.get("sector","ENERGY")).upper()}</span><b>{esc(t(x))}</b><span class="more">ЧИТАТИ НА САЙТІ IIG →</span></a>' for x in news)
advice_cards="".join(f'<a class="advice-card" href="{link("advice",x["slug"])}"><b>{esc(t(x))}</b><span>Читати →</span></a>' for x in advice)
doc=f'''<!doctype html><html lang="uk"><head><meta charset="utf-8"><title>IIG Monthly Digest — Вересень 2026</title><style>
@page{{size:1536px 1024px;margin:0}}*{{box-sizing:border-box}}html,body{{margin:0;font-family:Arial,sans-serif;color:#10243b;background:#fff}}a{{color:inherit;text-decoration:none}}
.page{{width:1536px;height:1024px;page-break-after:always;position:relative;overflow:hidden;background:#fff}}.page:last-child{{page-break-after:auto}}
.cover{{display:grid;grid-template-columns:47% 53%}}.hero{{position:relative;padding:54px 55px;color:#fff;background:#092c4d url("../assets/home-hero-approved.webp") center/cover no-repeat}}.hero:before{{content:"";position:absolute;inset:0;background:linear-gradient(180deg,rgba(5,28,49,.76),rgba(5,28,49,.91))}}.hero>*{{position:relative}}.brand{{font-size:52px;font-weight:800}}.brand small{{font-size:15px;margin-left:18px;vertical-align:middle}}h1{{font-size:54px;line-height:.95;margin:70px 0 10px}}.sub{{font-size:27px;font-weight:700}}.month{{display:inline-block;margin-top:25px;background:#e9372c;padding:12px 18px;font-weight:800;font-size:18px}}.mission{{font-size:26px;line-height:1.25;font-weight:700;margin-top:28px}}.hero-foot{{position:absolute;left:55px;right:55px;bottom:45px;border-top:1px solid rgba(255,255,255,.45);padding-top:20px;font-size:17px}}.index{{padding:38px 34px;background:#f7f9fc}}.index h2,.page2 h2{{margin:0 0 18px;font-size:26px;color:#153d72}}.news-grid{{display:grid;grid-template-columns:1fr;gap:9px}}.news-card{{display:grid;grid-template-columns:118px 1fr 145px;gap:13px;align-items:center;background:#fff;border:1px solid #dce4ee;border-radius:10px;padding:12px 14px;min-height:72px}}.news-card b{{font-size:17px;line-height:1.15}}.sector{{font-size:11px;font-weight:800;color:#153d72}}.more{{font-size:11px;font-weight:800;color:#e9372c;text-align:right}}.foot{{position:absolute;bottom:15px;right:25px;font-size:11px;color:#64748b}}
.page2{{padding:38px 48px;background:#f7f9fc}}.page2 .top{{display:grid;grid-template-columns:1fr 330px;gap:28px;align-items:start}}.advice-grid{{display:grid;grid-template-columns:1fr 1fr;gap:13px}}.advice-card{{min-height:118px;background:#fff;border:1px solid #dce4ee;border-radius:10px;padding:18px;display:flex;flex-direction:column;justify-content:space-between}}.advice-card b{{font-size:18px;line-height:1.2}}.advice-card span{{font-size:12px;color:#5d33a6;font-weight:800}}.engineer{{height:285px;border-radius:12px;background:#173d64 url("../assets/chief-engineer-approved.webp") center/cover no-repeat;position:relative;overflow:hidden}}.engineer:after{{content:"ПОРАДИ ГОЛОВНОГО ІНЖЕНЕРА";position:absolute;left:0;right:0;bottom:0;padding:18px;color:#fff;font-weight:800;background:linear-gradient(transparent,rgba(3,23,42,.92))}}.cta-row{{display:flex;gap:16px;margin-top:22px}}.cta{{padding:15px 22px;border-radius:8px;background:#153d72;color:#fff;font-weight:800}}.cta.red{{background:#e9372c}}
</style></head><body>
<section class="page cover"><div class="hero"><div class="brand">IIG <small>INDUSTRY INTELLIGENCE GENERATION</small></div><h1>MONTHLY DIGEST</h1><div class="sub">ПРОМИСЛОВОЇ ЕНЕРГЕТИКИ</div><div class="month">ВЕРЕСЕНЬ 2026</div><div class="mission">Енергія відновлення.<br>Інвестиції в майбутнє<br>промисловості України</div><div class="hero-foot">{len(news)} перевірених публікацій · 9 галузей · активні посилання на IIG</div></div><div class="index"><h2>КЛЮЧОВІ НОВИНИ ВИПУСКУ</h2><div class="news-grid">{news_cards}</div></div><div class="foot">IIG Monthly Digest · Вересень 2026 · 1/2</div></section>
<section class="page page2"><div class="top"><div><h2>ПОРАДИ ГОЛОВНОГО ІНЖЕНЕРА</h2><div class="advice-grid">{advice_cards}</div></div><div><div class="engineer"></div><div class="cta-row"><a class="cta red" href="{BASE}forms.html#project">РОЗМІСТИТИ ПРОЄКТ</a></div><div class="cta-row"><a class="cta" href="{BASE}forms.html#subscribe">ПІДПИСАТИСЯ</a></div></div></div><div class="foot">IIG Monthly Digest · Вересень 2026 · 2/2</div></section>
</body></html>'''
(ROOT/"digest/2026-09-review.html").write_text(doc,encoding="utf-8")
print("DIGEST_RELEASE_HTML_PASS",{"news":len(news),"advice":len(advice)})
