from pathlib import Path
import re, json, sys
root=Path(".")
html=(root/"admin-ua.html").read_text(encoding="utf-8")
js=(root/"assets/admin.js").read_text(encoding="utf-8")
contacts=(root/"assets/admin-contacts.js").read_text(encoding="utf-8")
spec=(root/"ADMIN_MASTER_SPEC.md").read_text(encoding="utf-8")
errors=[]
def need(cond,msg):
    if not cond: errors.append(msg)
for s in ["Новини та публікації","Дайджест","Розсилка та база","Користувачі та права","Безпека"]:
    need(s in html,f"UA navigation missing: {s}")
need("contentTypeFilter" in html,"Content type filter missing")
need("masterdigest" in html and "digestMasterFrame" in html,"Approved Digest MASTER viewer missing")
need(html.count('class="btn primary masterPage')==3,"Digest MASTER must expose exactly 3 page controls")
need("6003552eed45f96e32bc1794b2297a04adef84dd319595844cebef57118111fc" in html,"Approved Digest MASTER SHA missing")
need("digest/admin-master-2026-09-v2.html" in html and "DIGEST_MASTER_VIEW" in js,"Approved Digest MASTER v2 route missing")
need("digest/IIG-Monthly-Digest-2026-09.pdf" not in html and "DIGEST_MASTER_PDF" not in js,"Admin MASTER still points to legacy public PDF")
master=(root/"digest/admin-master-2026-09-v2.html").read_text(encoding="utf-8")
need("IIG_Monthly_Digest_2026-09_FINAL_DEMO (2)" in master,"MASTER v2 source identity missing")
need("УКРАЇНА ТА СВІТ — 15 ПОДІЙ У ФОКУСІ" in master and "ФІНАНСИ · РЕГУЛЮВАННЯ · ІНЖЕНЕРНА ПРАКТИКА" in master,"MASTER v2 pages 2/3 missing")
need(".cta{padding:13px 8px;border-radius:7px;text-align:center;font-size:14px;font-weight:900;color:#fff}" in master,"Page 1 CTA white 2x font lock missing")
need(".advctas div{padding:13px 6px;text-align:center;border-radius:4px;font-size:12px;font-weight:900;color:#fff}" in master,"Page 3 CTA white 2x font lock missing")
need("projectRequests" in html and "subscribeRequests" in html and "engineerRequests" in html,"Request moderation cards missing")
need("ADMIN_1" in html and "Igor Kryvoshei" in html and "develop.iig@gmail.com" in html,"ADMIN_1 profile missing")
need("+38 067 5063591" in html,"ADMIN_1 phone missing")
need("ADMIN_1 approval required" in html,"ADMIN_1 security approval rule missing")
need("xlsxStatus" in html,"XLSX non-blocking status area missing")
need("rejectDemo" in html and "Відхилити" in html,"Reject workflow missing")
need("accept=\".csv,.xlsx" in html,"CSV/XLSX UI contract missing")
need('const STATE={DRAFT:' in js,"Stable machine state map missing")
need('n.status="DRAFT"' in js and 'n.status="APPROVED"' in js and 'n.status="REJECTED"' in js,"Content state transitions incomplete")
need('public-advice.json' in js,"Chief Engineer Advice is not in CMS")
need("DIGEST_RELEASE_BLOCKED" in js,"Digest direct-link gate missing")
need("PAGE_CAPACITY" in js and "slotCost" in js and "pageFree" in js and "autoFillDigest" in js,"Digest page-capacity packing missing")
need("changeDigestIssue" in html and "digestIssueBadge" in html and "MONTHS_UA" in js,"Digest month/year control missing")
need("digestRubricFilter" in html and "RUBRIC_LABEL" in js and "rubrichead" in js,"Digest rubric grouping missing")
need("ЗАТВЕРДЖЕНО ДО ПУБЛІКАЦІЇ" in js and "approvalState" in html,"Green publication approval state missing")
need("fixedAdvice" in js and "kind===\"finance\"" in js,"Fixed Chief Engineer Advice block contract missing")
news_data=json.loads((root/"content/public-news.json").read_text(encoding="utf-8"))
news_items=news_data if isinstance(news_data,list) else news_data.get("items",[])
finance_items=[x for x in news_items if x.get("digest_rubric")=="FINANCE"]
reg_items=[x for x in news_items if x.get("digest_rubric")=="REGULATION"]
need(len(finance_items)>=5 and len(reg_items)>=5,"Finance/Regulation editorial pool missing")
need("ФІНАНСИ" in js and "ЗАКОНОДАВСТВО / РЕГУЛЮВАННЯ" in js,"Finance/Legislation rubric labels missing")
need("digest_rubric" in js,"Explicit digest rubric override missing")
need("article.html?id=" in js,"NEWS direct-link route must use article.html?id")
need("coverBgFile" in html and "coverTitle" in html and "coverAnnouncement" in html,"Cover page editor missing")
need("IMAGE_RULES" in js and "validateDigestImage" in js and "1200" in js and "1697" in js,"Digest background image quality gate missing")
need("extraPageEditor" in html and "extraPageType" in html and "saveExtraPage" in html,"Flexible page 4+ editor missing")
need("IIG_ORIGINAL" in html and "SUCCESS_PROJECT" in html and "SPONSORED" in html,"Page 4+ content types missing")
need("extraPageMarkup" in js and 'kind:"promo"' in js,"Flexible promotional page renderer missing")
need("extraPageOverlay" in html and "extraPageBgPosition" in html and "extraAnnouncement" in html,"Page 4+ must mirror cover background/announcement controls")
need('const extras=digestPages.filter(p=>p.kind==="promo"||p.kind==="article")' in js and 'digestPages.push(...extras)' in js,"Auto-pack/compact must preserve promo + imported article pages 4+")
need("validInternalOrHttps" in js and "badPromo" in js,"Page 4+ CTA/direct-link release gate missing")
need("articleSourceFile" in html and "buildArticlePages" in html and "articleImportBody" in html,"Article file importer missing")
need("parseDocx" in js and "openZip" in js and "DecompressionStream" in js,"Local DOCX parser missing")
need("ARTICLE_PAGE_CAPACITY" in js and "paginateArticleMaterial" in js and "articleBlockCost" in js,"Article auto-pagination missing")
need("articlePageMarkup" in js and "ПІДПИСАТИСЯ НА ДАЙДЖЕСТ" in js,"Page-2 canvas / Subscribe CTA missing")
need('p.kind==="promo"||p.kind==="article"' in js,"Core repack must preserve imported article pages")
need("ARTICLE_IMAGE_MIN_LONG_SIDE" in js,"Imported image quality gate missing")
need("DOCX/TXT/MD/RTF/HTML" in html,"Supported editor file types not disclosed")
need("APPROVED MASTER v2 · Page 1" in js and "masterfallback" in js and "isDefault:true" in js,"No-change cover must fall back to approved MASTER")
need("edDigestRubric" in html and "digest_rubric" in js,"Independent Digest rubric editor missing")
for sector in ["food","logistics","datacenters","chemical","waste"]:
    need(f'value="{sector}"' in html,f"CMS sector missing: {sector}")
need("parseAdviceSections" in js and 'base.sections=parseAdviceSections' in js,"Advice edits do not round-trip structured sections")
need("EDITORIAL_SESSION_KEY" in js and "persistEditorial" in js and "restoreEditorial" in js,"Editorial session persistence missing")
need("releaseReadiness" in html and "renderReleaseReadiness" in js,"New-issue readiness panel missing")
need("sourceHealthSummary" in html and "technical_url_verified" in js and "feed_verified" in js,"Source technical-health operator view missing")
need('class="btn lock" data-locked=' in html,"Website locked controls remain inert")
need("step26-admin1-rights-fastpath-20261002" in html,"Admin asset cache-busting version not advanced")
need(html.count('<option value="APPROVED">')==1,"Duplicate APPROVED status filter remains")
need("issueMatches" in js and "publication_date" in js,"Monthly Digest issue filter missing")
candidate=json.loads((root/"content/digest-issues/2026-09-admin-candidate.json").read_text(encoding="utf-8"))
need(candidate.get("issue")=="2026-09" and candidate.get("status")=="AWAITING_ADMIN_REVIEW","September Admin Digest candidate must await ADMIN_1 review")
need(candidate["counts"].get("general",0)==23 and candidate["counts"].get("finance",0)==7 and candidate["counts"].get("regulation",0)==7 and candidate["counts"].get("advice_pool",0)>=3 and candidate["counts"].get("advice_selected",0)==3,"September candidate content pool incomplete")
need("digest_title" in js and "fullTitle" in js,"Digest digest_title policy missing")
need("finalPreviewDigest" in html and "finalPreviewState" in html and "openFinalDigestPreview" in js,"Final Digest layout preview missing")
need("newsImagePanel" in html and "newsImageMode" in html and "newsImageFile" in html and "newsImageRights" in html,"News image review panel missing")
need("необов’язково для ADMIN_1" in html and "OWNER_CONFIRMED" in js and "rights_verified_by" in js,"ADMIN_1 rights fast-path missing")
need('if(!credit)return gate("Для власного upload заповніть Credit / власник прав.");' not in js,"Credit must not remain mandatory for ADMIN_1 upload")
need("approveNewsImage" in js and "image_admin_approved" in js and "image_approved_by" in js,"Image approval workflow missing")
need('n.content_type==="NEWS"&&n.image_admin_approved!==true' in js,"NEWS approval must fail closed without image approval")
need("successGate" in js and "productionGate" in js and "modalTitle" in html,"Admin success and production modals are not separated")
need("ACTIVE_ADMIN" in js and 'id:"ADMIN_1"' in js and "editorial_authority:true" in js,"ADMIN_1 active editorial session missing")
need("production_authenticated:false" in js,"Demo ADMIN_1 must remain non-production authenticated")
need("requireAdmin1" in js and 'requireAdmin1("ЗАТВЕРДИТИ ФОТО")' in js and 'requireAdmin1("ЗАТВЕРДИТИ ДО ПУБЛІКАЦІЇ")' in js,"ADMIN_1 role gate missing on editorial approvals")
need("adminToast" in js and "admintoast" in html,"Non-blocking editorial success confirmation missing")
need("function publishDemo()" in js and 'requireAdmin1("ОПУБЛІКУВАТИ У DEMO")' in js,"Demo publish workflow missing")
need('n.status="PUBLISHED"' in js and "demo_published_by=ACTIVE_ADMIN.id" in js,"Demo publish state/audit identity missing")
need('$("#publishProd")' not in js,"Invalid publish selector")
need("Опублікувати у DEMO" in html and "productionGate" in js,"Demo publish label or production guard missing")
need("DIGEST_RELEASE_BLOCKED: усі NEWS" in js,"Final approval must require ADMIN_1 news approvals")
need("iig.step26.editorial.sep2026.admin1.v2" in js,"Editorial session version reset missing")
sept=[x for x in news_items if str(x.get("publication_date","")).startswith("2026-09") and not x.get("digest_exclude")]
need(len(sept)>=30 and all(x.get("status")=="REVIEW" and x.get("admin_approved") is False for x in sept),"September NEWS must start unconfirmed for ADMIN_1 review")
manifest=json.loads((root/"baze_foto_news/manifest.json").read_text(encoding="utf-8"))
need("rubric_fallback" in manifest and "FINANCE" in manifest["rubric_fallback"] and "REGULATION" in manifest["rubric_fallback"],"Finance/Regulation image fallback missing")

need("PR #10 • НЕ MERGED" in js,"Robot #7 honest main-state marker missing")
need("sourceRegistryPreview" in html and "loadSources" in js,"260 sources operator view missing")
need("demoAudit" in html and "auditEvent" in js,"Demo audit trail missing")
need("PENDING" in contacts and "SUPPRESSED" in contacts and "ACTIVE" in contacts,"Consent state model incomplete")
need("window.IIGContacts" in contacts,"Request-to-contact bridge missing")
need(".xlsx" in contacts and "MASTER XLSX прийнято" in contacts,"XLSX safe acceptance status missing")
need("SUPPRESSED" in spec and "ADMIN_1" in spec,"Owner review governance spec missing")
need("NO_AUTO_PUBLISH" in spec and "ADMIN_ONLY" in spec,"Admin publication hard rules missing")
need("PASSWORD_OK != ADMIN_ACCESS" in spec,"Authentication invariant missing")
need("\\nfunction" not in js,"Literal escaped newline corrupts JavaScript")
need("n.status=statusUA" not in js,"Display localization corrupts machine status")
need("password" not in html.lower() or "production" in html.lower(),"Unexpected password material")
reg=json.loads((root/"content/discovery/IIG_news_source_registry_260.json").read_text(encoding="utf-8"))
sources=reg if isinstance(reg,list) else reg.get("sources",[])
need(len(sources)==260,f"Source registry expected 260, found {len(sources)}")
if errors:
    print("STEP 26 ADMIN MASTER: FAIL")
    for e in errors: print("-",e)
    sys.exit(1)
print("STEP 26 ADMIN MASTER: 10/10 STATIC ACCEPTANCE GREEN")
print("UA / UX / CMS / REVIEW / DIGEST / MAILING / RADAR / ROBOTS / SECURITY / E2E-CONTRACT = PASS")
