from pathlib import Path
import re, json, sys
root=Path(".")
html=(root/"admin-ua.html").read_text(encoding="utf-8")
final_admin=(root/"admin-final-admin1-v1.html").read_text(encoding="utf-8")
source_js=(root/"assets/admin.js").read_text(encoding="utf-8")
live_js_path=root/"assets/admin-final-admin1-v1.js"
js=live_js_path.read_text(encoding="utf-8")
need_live_runtime=True
pub=(root/"assets/public-news.js").read_text(encoding="utf-8")
contacts=(root/"assets/admin-contacts.js").read_text(encoding="utf-8")
spec=(root/"ADMIN_MASTER_SPEC.md").read_text(encoding="utf-8")
errors=[]
def need(cond,msg):
    if not cond: errors.append(msg)
need(live_js_path.is_file(),"Cache-proof live Admin runtime missing")
need('assets/admin-final-admin1-v1.js' in html,"Admin HTML must load cache-proof live runtime")
need('assets/admin-final-admin1-v1.js?v=MANUAL-FIRST-NO-REBUILD-V3' in final_admin,"Dedicated FINAL_ADMIN_IIG page missing cache-proof runtime")
need('data-admin-runtime-page="ADMIN1_FINAL_LOCK_V1"' in final_admin,"Dedicated FINAL_ADMIN_IIG runtime marker missing")
need("RUNTIME · ADMIN1 FINAL LOCK v1" in html,"Visible Admin runtime version badge missing")
need('IIG_ADMIN_RUNTIME_VERSION="ADMIN1_ATOMIC_FINAL_LOCK_V1"' in js,"Live runtime version marker missing")
need(source_js==js,"Source admin.js and live cache-proof runtime must remain byte-identical")

for s in ["Новини та публікації","Дайджест","Розсилка та база","Користувачі та права","Безпека"]:
    need(s in html,f"UA navigation missing: {s}")
need("contentTypeFilter" in html,"Content type filter missing")
need("masterdigest" in html and "digestMasterFrame" in html,"Approved Digest MASTER viewer missing")
need(html.count('class="btn primary masterPage')==3,"Digest MASTER must expose exactly 3 page controls")
need("6003552eed45f96e32bc1794b2297a04adef84dd319595844cebef57118111fc" in html,"Approved Digest MASTER SHA missing")
need("digest/admin-master-2026-09-v2.html" in html and "DIGEST_MASTER_VIEW" in js,"Approved Digest MASTER v2 route missing")
need("digest/IIG-Monthly-Digest-2026-09.pdf" not in html and "DIGEST_MASTER_PDF" not in js,"Admin MASTER still points to legacy public PDF")
master=(root/"digest/admin-master-2026-09-v2.html").read_text(encoding="utf-8")
need("IIG_Monthly_Digest_2026-09_FINAL_DEMO (2)" in master,"MASTER v2 source identity missing")
need("УКРАЇНА ТА СВІТ — 15 ПОДІЙ У ФОКУСІ" in master and "ФІНАНСИ · РЕГУЛЮВАННЯ · ІНЖЕНЕРНА ПРАКТИКА" in master,"MASTER v2 pages 2/3 missing")
need(".cta{padding:13px 8px;border-radius:7px;text-align:center;font-size:14px;font-weight:900;color:#fff}" in master,"Page 1 CTA white 2x font lock missing")
need(".advctas div{padding:13px 6px;text-align:center;border-radius:4px;font-size:12px;font-weight:900;color:#fff}" in master,"Page 3 CTA white 2x font lock missing")
need("projectRequests" in html and "subscribeRequests" in html and "engineerRequests" in html,"Request moderation cards missing")
need("ADMIN_1" in html and "Igor Kryvoshei" in html and "develop.iig@gmail.com" in html,"ADMIN_1 profile missing")
need("+38 067 5063591" in html,"ADMIN_1 phone missing")
need("ADMIN_1 approval required" in html,"ADMIN_1 security approval rule missing")
need("xlsxStatus" in html,"XLSX non-blocking status area missing")
need("rejectDemo" in html and "Відхилити" in html,"Reject workflow missing")
need("accept=\".csv,.xlsx" in html,"CSV/XLSX UI contract missing")
need('const STATE={DRAFT:' in js,"Stable machine state map missing")
need('n.status="DRAFT"' in js and 'n.status="APPROVED"' in js and 'n.status="REJECTED"' in js,"Content state transitions incomplete")
need('public-advice.json' in js,"Chief Engineer Advice is not in CMS")
need("DIGEST_RELEASE_BLOCKED" in js,"Digest direct-link gate missing")
need("PAGE_CAPACITY" in js and "slotCost" in js and "pageFree" in js and "autoFillDigest" in js,"Digest page-capacity packing missing")
need("changeDigestIssue" in html and "digestIssueBadge" in html and "MONTHS_UA" in js,"Digest month/year control missing")
need("digestRubricFilter" in html and "RUBRIC_LABEL" in js and "rubrichead" in js,"Digest rubric grouping missing")
need("ЗАТВЕРДЖЕНО ДО ПУБЛІКАЦІЇ" in js and "approvalState" in html,"Green publication approval state missing")
need("fixedAdvice" in js and "kind===\"finance\"" in js,"Fixed Chief Engineer Advice block contract missing")
news_data=json.loads((root/"content/public-news.json").read_text(encoding="utf-8"))
news_items=news_data if isinstance(news_data,list) else news_data.get("items",[])
finance_items=[x for x in news_items if x.get("digest_rubric")=="FINANCE"]
reg_items=[x for x in news_items if x.get("digest_rubric")=="REGULATION"]
need(len(finance_items)>=5 and len(reg_items)>=5,"Finance/Regulation editorial pool missing")
need("ФІНАНСИ" in js and "ЗАКОНОДАВСТВО / РЕГУЛЮВАННЯ" in js,"Finance/Legislation rubric labels missing")
need("digest_rubric" in js,"Explicit digest rubric override missing")
need("article.html?id=" in js,"NEWS direct-link route must use article.html?id")
need("coverBgFile" in html and "coverTitle" in html and "coverAnnouncement" in html,"Cover page editor missing")
need("coverBgRights" in html and "approveCoverBg" in html and "coverBgApprovalState" in html,"Digest cover ADMIN_1 rights/apply confirmation UI missing")
need("bgRightsVerification" in js and "OWNER_CONFIRMED" in js and "ЗАТВЕРДИТИ ФОН ОБКЛАДИНКИ" in js,"Digest cover ADMIN_1 rights gate missing")
need("url('+c.bgData+')" in js,"Digest cover data URL renderer regression: custom background may collapse to fallback color")
need("Фон обкладинки підтверджено ADMIN_1" in js,"Final Digest QA must include cover-background ADMIN_1 approval")
need("digestcover-brand" in js and "digestcover-kpis" in js and "digestcover-ctas" in js,"Custom Digest cover must preserve approved MASTER v2 composition")
need("forms.html#project" in js and "forms.html#subscribe" in js,"Digest cover primary CTA routes missing")
need("industry.html?sector=energy" in js and "finance-news.html" in js and "advice.html" in js,"Digest cover thematic links missing")
need("DIGEST COVER — APPROVED MASTER v2 LOCKED GEOMETRY" in (root/"assets/admin.css").read_text(encoding="utf-8"),"Digest cover MASTER geometry CSS lock missing")
need("IMAGE_RULES" in js and "validateDigestImage" in js and "1200" in js and "1697" in js,"Digest background image quality gate missing")
need("extraPageEditor" in html and "extraPageType" in html and "saveExtraPage" in html,"Flexible page 4+ editor missing")
need("IIG_ORIGINAL" in html and "SUCCESS_PROJECT" in html and "SPONSORED" in html,"Page 4+ content types missing")
need("extraPageMarkup" in js and 'kind:"promo"' in js,"Flexible promotional page renderer missing")
need("extraPageOverlay" in html and "extraPageBgPosition" in html and "extraAnnouncement" in html,"Page 4+ must mirror cover background/announcement controls")
need('const extras=digestPages.filter(p=>p.kind==="promo"||p.kind==="article")' in js and 'digestPages.push(...extras)' in js,"Auto-pack/compact must preserve promo + imported article pages 4+")
need("validInternalOrHttps" in js and "badPromo" in js,"Page 4+ CTA/direct-link release gate missing")
need("articleSourceFile" in html and "buildArticlePages" in html and "articleImportBody" in html,"Article file importer missing")
need("parseDocx" in js and "openZip" in js and "DecompressionStream" in js,"Local DOCX parser missing")
need("ARTICLE_PAGE_CAPACITY" in js and "paginateArticleMaterial" in js and "articleBlockCost" in js,"Article auto-pagination missing")
need("articlePageMarkup" in js and "ПІДПИСАТИСЯ НА ДАЙДЖЕСТ" in js,"Page-2 canvas / Subscribe CTA missing")
need('p.kind==="promo"||p.kind==="article"' in js,"Core repack must preserve imported article pages")
need("ARTICLE_IMAGE_MIN_LONG_SIDE" in js,"Imported image quality gate missing")
need("DOCX/TXT/MD/RTF/HTML" in html,"Supported editor file types not disclosed")
need("APPROVED MASTER v2 · Page 1" in js and "masterfallback" in js and "isDefault:true" in js,"No-change cover must fall back to approved MASTER")
need("edDigestRubric" in html and "digest_rubric" in js,"Independent Digest rubric editor missing")
for sector in ["food","logistics","datacenters","chemical","waste"]:
    need(f'value="{sector}"' in html,f"CMS sector missing: {sector}")
need("parseAdviceSections" in js and 'base.sections=parseAdviceSections' in js,"Advice edits do not round-trip structured sections")
need("EDITORIAL_SESSION_KEY" in js and "persistEditorial" in js and "restoreEditorial" in js,"Editorial session persistence missing")
need("releaseReadiness" in html and "renderReleaseReadiness" in js,"New-issue readiness panel missing")
need("sourceHealthSummary" in html and "technical_url_verified" in js and "feed_verified" in js,"Source technical-health operator view missing")
need('class="btn lock" data-locked=' in html,"Website locked controls remain inert")
need("digest-row-lock-manual-authority-v2-20261003" in html,"Admin asset cache-busting version not advanced")
need(html.count('<option value="APPROVED">')==1,"Duplicate APPROVED status filter remains")
need("issueMatches" in js and "publication_date" in js,"Monthly Digest issue filter missing")
candidate=json.loads((root/"content/digest-issues/2026-09-admin-candidate.json").read_text(encoding="utf-8"))
need(candidate.get("issue")=="2026-09" and candidate.get("historical_snapshot") is True and candidate.get("release_authority") is False,"September Digest snapshot must be historical/non-authoritative")
need("content/digest-issues/2026-09-admin-candidate.json" not in js,"Admin runtime must not use historical Digest snapshot as release authority")
need("digest_title" in js and "fullTitle" in js,"Digest digest_title policy missing")
need("finalPreviewDigest" in html and "finalPreviewState" in html and "openFinalDigestPreview" in js,"Final Digest layout preview missing")
need("preview_completed" in js and "preview_fingerprint" in js and "review_snapshot" in js,"Final Preview audit/snapshot state missing")
need('id="approveDigestProd"' in html and 'ЗАТВЕРДИТИ ФІНАЛЬНИЙ МАКЕТ' in html,"Red Final Approval control missing")
need("iig.digest-final-preview-snapshot.v1" in js and "review_snapshot" in js,"Final Preview snapshot contract missing")
need("AWAITING_ADMIN_1_ATOMIC_LOCK" in js,"Preview snapshot must await ADMIN_1 lock authority")
need("ADMIN_1_ATOMIC_FINAL_LOCK" in js and "layout_locked_by=\"ADMIN_1\"" in js,"ADMIN_1 atomic final-lock authority missing")
need('snap.fingerprint!==fp' in js and 'preview_fingerprint!==fp' in js,"ADMIN_1 must approve only the exact latest Final Preview snapshot")
need("Fingerprint Final Preview snapshot став canonical candidate fingerprint" in js,"Red approval must promote preview fingerprint to canonical candidate")
need("ADMIN_1_LOCKED_AND_APPROVED" in js,"Approved snapshot terminal state missing")
need("Сформуйте release-candidate повторно" not in js,"Live Admin runtime still contains forbidden candidate rebuild message")
need("Сформуйте candidate повторно" not in js,"Live Admin runtime still contains forbidden candidate rebuild message")
need("Формувати candidate повторно не потрібно" in js or "Повторно формувати candidate не потрібно" in js,"Live Admin runtime must explicitly avoid candidate rebuild after edits")

need("digestCandidateChecks" in js,"Candidate build checks must be separate from final approval checks")
need("DIGEST_LAYOUT_KEY" in js and "persistDigestLayout" in js and "restoreDigestLayout" in js,"Manual Digest layout persistence contract missing")
need("layout_authority:\"MANUAL_AFTER_INITIAL_BUILD\"" in js and "auto_fill_policy:\"INITIAL_BUILD_OR_EXPLICIT_BUTTON_ONLY\"" in js,"Candidate must hand authority to manual layout after initial build")
need("ADMIN_1_APPROVED_MANUAL_LAYOUT" in js and "DISABLED_AFTER_CANDIDATE_BUILD" in js,"ADMIN_1 final approval must canonize manual layout and disable automatic refill authority")
need("renderReleaseReadiness();autoFillDigest(false)" not in js,"Editorial approve/publish/reject must never auto-refill an existing Digest layout")
need("const restoredLayout=restoreDigestLayout()" in js and "if(restoredLayout){renderDigest()}else{autoFillDigest(false)}" in js,"Admin load must restore manual layout before any auto-fill")
need("Автозаповнення ПЕРЕЗБЕРЕ поточний ручний макет" in js,"Explicit Auto-fill must warn that it replaces manual layout")
need("commitManualDigestEdit" in js and "invalidatePreviewAfterManualEdit" in js,"Manual Digest edits must persist and invalidate stale Preview")
need("ensureManualCandidateFromCurrentLayout" in js and "MANUAL_CURRENT_DIGEST_BOOTSTRAP" in js,"CURRENT manual Digest must bootstrap technical release envelope automatically")
need('auto_fill_policy:"FORBIDDEN_FOR_BOOTSTRAP"' in js,"Manual bootstrap must forbid Auto-fill")
need("РУЧНИЙ МАКЕТ · READY FOR FINAL PREVIEW" in js,"Missing-candidate state must defer to current manual Digest")
need("Спочатку один раз сформуйте актуальний release-candidate" not in js,"Final Preview must never require candidate rebuild")
need("спочатку один раз сформуйте release-candidate" not in js,"Red Final Approval must never require candidate rebuild")


need("спочатку ADMIN_1 має підтвердити всі NEWS поточного місяця" not in js,"Final Preview must not be blocked by unrelated monthly NEWS")
need("поточна редакція не збігається з останнім Final Preview snapshot" in js,"Final approval must require exact latest Final Preview snapshot")
need("newsImagePanel" in html and "newsImageMode" in html and "newsImageFile" in html and "newsImageRights" in html,"News image review panel missing")
need("edHomepageTop5" in html and "homepage_top5" in js,"Homepage TOP-5 admin control missing")
need("edHomepageTop5" in html and "homepage_top5" in js,"TOP-5 checkbox must be independent from mandatory publication destinations")
need("publicationDestinations" in js and "news_insights:true" in js,"Admin publication destinations contract missing")
need("publishedDestinations" in pub and "news_insights:true" in pub,"Public publication destinations contract missing")
need("ПОПЕРЕДНІЙ ПЕРЕГЛЯД СТАТТІ" in js and "adminarticlepreview" in js,"Admin full article preview missing")
need("newsTitlePreview" in js and "miniPreview" in js and "previewAdminArticle" in js,"Inline list article preview missing")
css=(root/"assets/admin.css").read_text(encoding="utf-8")
need("article-preview-mode" in js and "max-height:92vh" in css and "overflow:auto" in css,"Scrollable article preview missing")
need("IIG_EDITORIAL_EMPHASIS_V2" in js and "IIG_EDITORIAL_EMPHASIS_V2" in pub,"Shared editorial emphasis standard missing")
need("PERCENT_EMPHASIS_V3" in js and "PERCENT_EMPHASIS_V3" in pub,"Percent emphasis regression guard missing")
need("PERCENT_EMPHASIS_V3=true" in js and "%)(?=" in js and "PERCENT_EMPHASIS_V3=true" in pub and "%)(?=" in pub,"Percent matcher missing")
for token in ["CAPEX","вересня","CEO","МВт"]:
    need(token in js and token in pub,f"Editorial emphasis token missing: {token}")
schedule=json.loads((root/"content/news-update-schedule.json").read_text(encoding="utf-8"))
need(schedule.get("timezone")=="Europe/Prague" and schedule.get("weekday")=="MO","Weekly news schedule timezone/day missing")
need(schedule.get("window_local",{}).get("start")=="09:00" and schedule.get("window_local",{}).get("end")=="10:00","Weekly news update window must be 09:00-10:00")
need(schedule.get("output_state")=="REVIEW" and schedule.get("auto_publish") is False and schedule.get("admin_gate",{}).get("role")=="ADMIN_1","Weekly cycle must end in REVIEW and require ADMIN_1")
need("APPROVAL_LEDGER_KEY" in js and "iig.admin.approval-ledger.v1" in js and "restoreApprovalLedger" in js,"Approval Ledger preservation missing")
need("freezeApprovedSet" in js and "freezeApprovedSet" in html,"Bulk approved-material freeze missing")
need("manualNewsRefresh" in js and "manualNewsRefresh" in html and "editorial-refresh.yml" in html,"Manual ADMIN_1 NEWS refresh control missing")
need("dashboardNewsRefresh" in html and "dashboardNewsRefreshElapsed" in html and "startDashboardNewsRefresh" in js,"Dashboard manual NEWS generation control missing")
need("10–20 хв" in html and "fmtElapsed" in js,"Dashboard NEWS generation timing indicator missing")
need(schedule.get("manual_trigger",{}).get("enabled") is True and schedule.get("manual_trigger",{}).get("role")=="ADMIN_1","Manual refresh schedule contract missing")
refresh=(root/".github/workflows/editorial-refresh.yml")
need(refresh.is_file(),"Canonical editorial refresh workflow missing")
refresh_text=refresh.read_text(encoding="utf-8")
for token in ["workflow_dispatch","Europe/Prague","ADMIN_REVIEW","auto_publish","scripts/news_source_discovery.py","scripts/content_engine.py","scripts/quality_gate.py","scripts/image_rights_robot.py"]:
    need(token in refresh_text,f"Editorial refresh workflow contract missing: {token}")
need("DEMO_EDITORIAL_KEY" in pub and "mergeDemoPublished" in pub and "demoPublished" in pub,"Published Admin Demo items are not bridged to public renderer")
need("PUBLIC_DEMO_PUBLISHED_KEY" in js and "PUBLIC_DEMO_PUBLISHED_KEY" in pub and "persistPublishedBridge" in js,"Dedicated published Demo bridge missing")
need('published?"ОПУБЛІКОВАНО"' in js,"Published list status must be explicit")
need("browserSafeNewsImage" in js,"Uploaded image must be resized for browser-safe persistence")
need("рок(?:ів|и|у)?" in js and "рок(?:ів|и|у)?" in pub and "турбін" in js and "турбін" in pub,"Contextual numeric emphasis expansion missing")
need("homepage_top5" in pub and "slice(0,5)" in pub,"Homepage TOP-5 renderer missing")
need("необов’язково для ADMIN_1" in html and "OWNER_CONFIRMED" in js and "rights_verified_by" in js,"ADMIN_1 rights fast-path missing")
need('if(!credit)return gate("Для власного upload заповніть Credit / власник прав.");' not in js,"Credit must not remain mandatory for ADMIN_1 upload")
need("approveNewsImage" in js and "image_admin_approved" in js and "image_approved_by" in js,"Image approval workflow missing")
need('n.content_type==="NEWS"&&n.image_admin_approved!==true' in js,"NEWS approval must fail closed without image approval")
need("successGate" in js and "productionGate" in js and "modalTitle" in html,"Admin success and production modals are not separated")
need("ACTIVE_ADMIN" in js and 'id:"ADMIN_1"' in js and "editorial_authority:true" in js,"ADMIN_1 active editorial session missing")
need("production_authenticated:false" in js,"Demo ADMIN_1 must remain non-production authenticated")
need("requireAdmin1" in js and 'requireAdmin1("ЗАТВЕРДИТИ ФОТО")' in js and 'requireAdmin1("ЗАТВЕРДИТИ ДО ПУБЛІКАЦІЇ")' in js,"ADMIN_1 role gate missing on editorial approvals")
need("adminToast" in js and "admintoast" in html,"Non-blocking editorial success confirmation missing")
need("function publishDemo()" in js and 'requireAdmin1("ОПУБЛІКУВАТИ У DEMO")' in js,"Demo publish workflow missing")
need('n.status="PUBLISHED"' in js and "demo_published_by=ACTIVE_ADMIN.id" in js,"Demo publish state/audit identity missing")
need('$("#publishProd")' not in js,"Invalid publish selector")
need("Опублікувати у DEMO" in html and "productionGate" in js,"Demo publish label or production guard missing")
need("Матеріали candidate підтверджені ADMIN_1" in js and "Непідтверджені матеріали всередині candidate" in js,"Final approval must require ADMIN_1 approval for every included candidate item")
need("iig.step26.editorial.sep2026.admin1.v2" in js,"Editorial session version reset missing")
sept=[x for x in news_items if str(x.get("publication_date","")).startswith("2026-09") and not x.get("digest_exclude")]
need(len(sept)>=30 and all(x.get("status")=="REVIEW" and x.get("admin_approved") is False for x in sept),"September NEWS must start unconfirmed for ADMIN_1 review")
manifest=json.loads((root/"baze_foto_news/manifest.json").read_text(encoding="utf-8"))
need("rubric_fallback" in manifest and "FINANCE" in manifest["rubric_fallback"] and "REGULATION" in manifest["rubric_fallback"],"Finance/Regulation image fallback missing")

need("PR #10 • НЕ MERGED" in js,"Robot #7 honest main-state marker missing")
need("sourceRegistryPreview" in html and "loadSources" in js,"260 sources operator view missing")
need("demoAudit" in html and "auditEvent" in js,"Demo audit trail missing")
need("PENDING" in contacts and "SUPPRESSED" in contacts and "ACTIVE" in contacts,"Consent state model incomplete")
need("window.IIGContacts" in contacts,"Request-to-contact bridge missing")
need(".xlsx" in contacts and "MASTER XLSX прийнято" in contacts,"XLSX safe acceptance status missing")
need("SUPPRESSED" in spec and "ADMIN_1" in spec,"Owner review governance spec missing")
need("NO_AUTO_PUBLISH" in spec and "ADMIN_ONLY" in spec,"Admin publication hard rules missing")
need("PASSWORD_OK != ADMIN_ACCESS" in spec,"Authentication invariant missing")
need("\\nfunction" not in js,"Literal escaped newline corrupts JavaScript")
need("n.status=statusUA" not in js,"Display localization corrupts machine status")
need("password" not in html.lower() or "production" in html.lower(),"Unexpected password material")
reg=json.loads((root/"content/discovery/IIG_news_source_registry_260.json").read_text(encoding="utf-8"))
sources=reg if isinstance(reg,list) else reg.get("sources",[])
need(len(sources)==260,f"Source registry expected 260, found {len(sources)}")
# Advice public renderer regression guards
advice_js=(root/"assets/public-advice.js").read_text(encoding="utf-8")
advice_data=json.loads((root/"content/public-advice.json").read_text(encoding="utf-8"))
approved_advice=[x for x in advice_data.get("items",[]) if x.get("status") in {"APPROVED","PUBLISHED"} and x.get("admin_approved") is True]
need(len(approved_advice)>=1,"Approved Advice registry unexpectedly empty")
need("MISSING_CONCEPTUAL_SCHEMATIC" in advice_js,"Advice renderer must fail closed without content-specific schematic")
need("if(!d)return url" not in advice_js,"Published Advice generic placeholder fallback must remain disabled")
need("['APPROVED','PUBLISHED'].includes(x.status)" in advice_js,"Advice public approval filter missing")

# Homepage Chief Engineer Advice latest-3 regression guards
home=(root/"index.html").read_text(encoding="utf-8")
advice_js=(root/"assets/public-advice.js").read_text(encoding="utf-8")
need('class="advice-mini"' in home,"Homepage Advice mini container missing")
need("assets/public-advice.js?v=advice-route-canonical-id-20261003" in home,"Homepage must load current Advice schematic renderer")
need("items.sort((a,b)=>String(b.publication_date" in advice_js,"Advice must sort newest-first by publication_date")
need("items.slice(0,6)" in advice_js,"Homepage must render exactly latest 6 Advice items")

# Industry NEWS card-layout regression guards
industry=(root/"industry.html").read_text(encoding="utf-8")
pubnews=(root/"assets/public-news.js").read_text(encoding="utf-8")
need("assets/public-news.js?v=industry-advice-card-layout-20261002" in industry,"Industry pages must load canonical published NEWS renderer")
need('id="industry-news-grid-v2"' in industry and "grid-template-columns:repeat(3" in industry,"Industry pages must use Advice-style card grid")
need("industryCard=x=>" in pubnews and "ЧИТАТИ НОВИНУ" in pubnews,"Industry NEWS card renderer missing")
need("renderItems();" not in industry[industry.find("window.addEventListener"):],"Legacy static industry demo renderer must not run")
sector_keys=["energy","metallurgy","food","logistics","datacenters","chemical","agriculture","pharma","waste"]
need(all(("industry.html?sector="+k) in home for k in sector_keys),"Homepage must expose all nine canonical industry routes")

# Digest pre-generation Red Team guards
need('id="digestOperatorRole"' in html and "ADMIN_2 · Digest Builder" in html,"Digest ADMIN_2 builder role missing")
need('id="generateDigestCandidate"' in html and "buildDigestReleaseCandidate" in js,"Generate-new-Digest action missing")
need("Відкрийте «ФІНАЛЬНИЙ ПЕРЕГЛЯД ВЕРСТКИ» ще раз. Повторно формувати candidate не потрібно." in js,"Final approval must require only a new exact Final Preview after edits")
need("3-PAGE STANDARD" in js and "digestOverflowExcluded" in js,"Automatic core Digest packing must stop at 3 pages")
need('digestPages.slice(3).filter(p=>["news","finance"].includes(p.kind))' in js,"Core NEWS/Finance Page 4+ release blocker missing")
need("Page 4+ додається тільки вручну" in html,"Admin instructions must reserve Page 4+ for manual IIG/partner/promo content")
need("requireDigestFinalApprover" in js and "ADMIN_1_APPROVED_DEMO_QA" in js,"ADMIN_1 final Digest approval gate missing")
need("CURRENT_APPROVAL_LEDGER_AND_CMS" in js,"Digest candidate must use current approved CMS/ledger state")
need('["APPROVED","PUBLISHED"].includes(n.status)' in js,"PUBLISHED approved NEWS must remain valid Digest input")
need("fixedAdvice" in js and "localeCompare" in js,"Digest fixed Advice must select newest three")
need("digest/2026-09-review.html" not in (root/"index.html").read_text(encoding="utf-8"),"Homepage still links legacy Digest HTML")
need("digest/2026-09-review.html" not in (root/"about.html").read_text(encoding="utf-8"),"About still links legacy Digest HTML")
need("digest/2026-09-review.html" not in (root/"case.html").read_text(encoding="utf-8"),"Case still links legacy Digest HTML")
need("digest/2026-09-review.html" not in (root/"industry.html").read_text(encoding="utf-8"),"Industry still links legacy Digest HTML")
need("digest/IIG-Monthly-Digest-2026-09.pdf" not in (root/"news.html").read_text(encoding="utf-8"),"News page still links legacy Digest PDF")
need("LEGACY_DIGEST_BUILD_DISABLED" in (root/".github/workflows/build-digest-pdf.yml").read_text(encoding="utf-8"),"Legacy Digest PDF workflow not disabled")

# Chief Engineer Advice schematic-quality gate
advice_js=(root/"assets/public-advice.js").read_text(encoding="utf-8")
advice_data=json.loads((root/"content/public-advice.json").read_text(encoding="utf-8"))
approved_advice=[x for x in advice_data.get("items",[]) if x.get("status") in {"APPROVED","PUBLISHED"} and x.get("admin_approved") is True]
missing_schematics=[x.get("slug") for x in approved_advice if ("'"+str(x.get("slug"))+"'") not in advice_js]
need(not missing_schematics,"Every approved Advice must have a dedicated conceptual schematic: "+",".join(missing_schematics))
need("MISSING_CONCEPTUAL_SCHEMATIC" in advice_js,"Advice renderer must fail closed when schematic is missing")
need("if(!d)return url('assets/iig-editorial-illustration.svg')" not in advice_js,"Published Advice generic illustration fallback is forbidden")

# Public UX regression: Advice cache, Digest public CTA and bilingual search
home=(root/"index.html").read_text(encoding="utf-8")
iig=(root/"assets/iig.js").read_text(encoding="utf-8")
advice_html=(root/"advice.html").read_text(encoding="utf-8")
advice_article=(root/"advice-article.html").read_text(encoding="utf-8")
need("advice-route-canonical-id-20261003" in advice_html and "advice-route-canonical-id-20261003" in advice_article and "advice-route-canonical-id-20261003" in home,"Advice conceptual-schematic cache version not advanced everywhere")
need("ПУБЛІКУЄТЬСЯ ТІЛЬКИ ПІСЛЯ ЗАТВЕРДЖЕННЯ ADMIN_1" not in home,"Internal ADMIN_1 Digest text must not be public")
need('class="download-circle"' in home and "↓" in home,"Digest CTA arrow must point downward")
need("digest/IIG-Monthly-Digest-2026-09.pdf" not in iig,"Public JS must not restore deleted legacy Digest PDF")
need("function initPublicSearch()" in iig and "runPublicSearch" in iig and "content/public-news.json" in iig and "content/public-advice.json" in iig,"Public bilingual search must be functional")
need("title?.ua" in iig and "title?.en" in iig and "summary?.ua" in iig and "summary?.en" in iig,"Search index must include both UA and EN content")
need("industry.html?sector=chemical" in iig and "Хімічна промисловість" in iig and "Chemical industry" in iig,"Search must index bilingual sector keywords")

# Public search source-of-truth / migration guards
iig=(root/"assets/iig.js").read_text(encoding="utf-8")
home=(root/"index.html").read_text(encoding="utf-8")
need("iig.step26.published.news.v1" in iig,"Search must include same-browser published NEWS bridge")
need("mergedNews=new Map()" in iig and "localNews=bridge.filter" in iig,"Search must merge repo and Admin-published NEWS")
need("SEARCH_STOPWORDS" in iig and "searchTokens" in iig,"Search must ignore conjunction stopwords")
need("єіб eib" in iig and "eib єіб" in iig,"Search must support EIB/ЄІБ bilingual alias")
need("finance-news.html?institution=eib" in iig,"Finance EIB page must be indexed")
need("digest-current-route-v4-20261003" in home,"Homepage search cache version not advanced")
need("advice-route-canonical-id-20261003" in home,"Homepage Advice route/schematic version must remain locked")
need('class="download-circle"' in home and "↓" in home,"Digest down-arrow migration invariant broken")

# Public search runtime regression guards
iig=(root/"assets/iig.js").read_text(encoding="utf-8")
home=(root/"index.html").read_text(encoding="utf-8")
need("const esc=s=>" in iig,"Search renderer HTML escape helper missing")
need("runPublicSearchSafe" in iig and "SEARCH_RUNTIME_ERROR" in iig,"Search runtime error guard missing")
need("digest-current-route-v4-20261003" in home,"Homepage search runtime cache version not advanced")

# About/contact project CTA routing
about=(root/"about.html").read_text(encoding="utf-8")
need('href="forms.html#project">SUBMIT YOUR PROJECT →</a>' in about,"About contact CTA must route to project form")


# Final pre-Digest runtime/integrity guards
news_page=(root/"news.html").read_text(encoding="utf-8")
need("+adviceMarkup+finalsubscribe" not in js,"Undefined finalsubscribe runtime reference remains in Final Preview")
need("function digestFingerprint()" in js and "fingerprint:digestFingerprint()" in js,"Digest release-candidate fingerprint missing")
need("snap.fingerprint!==fp" in js and "preview_fingerprint!==fp" in js,"ADMIN_1 approval must reject layout changes made after Final Preview")
need("ЗМІНИ ПІСЛЯ PREVIEW" in js,"Admin must visibly flag edits made after Final Preview")
need("fingerprintSafe" in js and "__BINARY_DATA__" in js,"Digest fingerprint must exclude embedded image bytes")
need("sessionStorage.setItem(DIGEST_CANDIDATE_KEY" in js,"Digest candidate sessionStorage quota fallback missing")
need("localStorage.getItem(DIGEST_CANDIDATE_KEY)||sessionStorage.getItem" in js,"Digest candidate restore fallback missing")
need("downloadDigestHtml" in html and "printDigestPdf" in html,"Admin-only Digest export controls missing")
need("buildStandaloneDigestHtml" in js and "downloadApprovedDigestHtml" in js and "printApprovedDigestPdf" in js,"Admin-only Digest artifact generator missing")
need("assertApprovedDigestArtifact" in js and "preview_fingerprint" in js,"Admin Digest export must be fingerprint-locked")
need("finaladvice-link" in js and "publicUrl(a)" in js,"Digest Advice items must remain clickable to exact Advice routes")
need("forms.html#project" in js and "forms.html#subscribe" in js,"Digest Advice CTA routes missing")
need("font-size:13.5px" in css and ".finaladvice-link" in css,"Digest Advice typography must remain 1.5x readable baseline")
need("digestEndCtas" in js and "digest-end-ctas" in css,"True final Digest page must contain mandatory Project + Subscribe CTA footer")
need("endCtas=i===1?digestSubscribeCta():(i>=2?digestEndCtas():"")" in js and "function digestEndCtas()" in js,"Digest Page 3 and every page 4+ must contain Project + Subscribe CTA footer")
need("forms.html#project" in js and "forms.html#subscribe" in js,"Mandatory Digest final CTA routes missing")
need('const DIGEST_PUBLISH_ENDPOINT="/api/v1/digest/releases"' in js,"Protected Digest publication endpoint contract missing")
need("archive_previous_current:true" in js and 'make_current:true' in js,"Digest publish must atomically archive previous CURRENT and promote new CURRENT")
need('mailing_state:"READY_FOR_MAILING"' in js and 'download_state:"READY_FOR_DOWNLOAD"' in js,"Published Digest must be ready for download and mailing")
need("PUBLISH_BACKEND_REQUIRED" in js,"Static Demo must fail closed when production publish backend is unavailable")
need('artifact_type:"ADMIN1_APPROVED_PDF"' in js and 'output_format:"PDF"' in js,"Canonical Digest release must upload the exact ADMIN_1 PDF artifact")
need('pdf_links_policy:"PRESERVE_ACTIVE_IIG_LINK_ANNOTATIONS"' in js and "digestSiteLinks" in js,"Digest PDF active-link preservation contract missing")
need('links_preserved!==true' in js and "PUBLIC_PDF_URL_REQUIRED" in js,"Digest publish must verify PDF URL and live link annotations")
need("packBalancedFinancePage" in js and "Math.abs(f-r)<=1" in js,"Page 3 Finance/Regulation balancing rule missing")
need("pi===1" in js and "digestbuilder-subscribe" in js,"Working Preview Page 2 must show Subscribe CTA")
need("pi>=2" in js and "digestbuilder-ctas" in js,"Working Preview must show dual CTA footer on Page 3 and every page 4+")
need("endCtas=i===1?digestSubscribeCta():(i>=2?digestEndCtas():"")" in js and "digestEndCtas" in js,"Final Preview/export must show CTA footer on Page 3 and every page 4+")
need(".digestbuilder-ctas" in css and ".digest-page-3 .digest-end-ctas" in css,"Page 3+ CTA layout CSS missing")
need("PAGE_CAPACITY={cover:0,news:23,finance:14}" in js,"Page 3 compact-row capacity must remain 14")
need("CORE DIGEST ROW GEOMETRY LOCK" in css and "grid-auto-rows:32px" in css,"Core Digest rows must use one immutable static geometry")
need(".digest-page-3 .finaladvice{margin-top:auto!important;position:static!important" in css,"Page 3 Advice must stay below identical fixed-height news rows")
need(".digest-page-3 .digest-end-ctas{margin-top:10px!important;position:static!important" in css,"Page 3 CTA must stay below Advice in normal flow")
need("finaldigest-readmore" in js and "Читати далі... →" in js,"Every Digest news row must expose explicit Read-more arrow")
need(".finaldigest-readmore" in css,"Digest Read-more arrow styling missing")
need("grid-auto-rows:max-content" in css and "align-content:start" in css,"Core Digest news rows must never stretch vertically")
need(".finalcorepage .finaldigestitem{display:grid;grid-template-columns:28px minmax(0,1fr)" in css and "height:32px" in css and "max-height:32px" in css,"Page 2/Page 3 news-row geometry must be identical and static")
need("digestSubscribeCta" in js and "digest-end-subscribe" in css,"Page 2 Subscribe CTA footer missing")
need('advice-article.html?id="+encodeURIComponent(n.slug)' in js,"New Digest Advice links must use canonical id route")
need("publishDigestSite" in html and "ЗАВАНТАЖИТИ PDF ДАЙДЖЕСТ НА САЙТ" in html,"Dedicated ADMIN PDF site-upload action missing")
need('output_format:"PDF"' in js and "PUBLISH_DIGEST_PDF" in js,"Admin site upload must publish PDF")
need("links_preserved!==true" in js,"PDF site upload must verify active link annotations")
need('advice-article.html?id="+encodeURIComponent(n.slug)' in js,"Admin must generate canonical Advice ?id= routes")
need("publishDigestSite" in html and "ЗАВАНТАЖИТИ PDF ДАЙДЖЕСТ НА САЙТ" in html and "digestPdfFile" in html,"Explicit Admin PDF publish-to-site control missing")
need('status:"READY_TO_PUBLISH"' in js,"ADMIN_1 approval must unlock READY_TO_PUBLISH state")
need("publishDigestSite" in js and "publishApprovedDigestToSite" in js,"Publish button handler missing")
need("pendingDigestPdf" in js and "new FormData()" in js and 'form.append("pdf",pendingDigestPdf' in js,"Admin must upload selected PDF binary via multipart form data")
advice_runtime=(root/"assets/public-advice.js").read_text(encoding="utf-8")
need("q.get('id')||q.get('slug')" in advice_runtime,"Public Advice must accept canonical id and legacy slug routes")
public_runtime=(root/"assets/iig.js").read_text(encoding="utf-8")
home=(root/"index.html").read_text(encoding="utf-8")
need("data-digest-current" in home,"Homepage current Digest control marker missing")
need('href="digest/current.html"' in home and 'href="news.html#digest"' not in home,"Digest download fallback must use dedicated CURRENT route, never NEWS")
need((root/"digest/current.html").is_file(),"Dedicated CURRENT Digest resolver page missing")
need('fetch("/api/v1/digest/current"' in public_runtime and 'd.status!=="CURRENT"' in public_runtime,"Public Digest card must resolve the server CURRENT release")
need("digest-current-route-v4-20261003" in home,"Public CURRENT Digest runtime cache-busting version not advanced")
need("public_release_path" not in js and "IIG-Monthly-Digest-2026-09-PUBLIC.pdf" not in js,"Admin runtime must not hardcode a hosting/public PDF release")
need("Build current public Digest PDF" not in (root/".github/workflows/pages.yml").read_text(encoding="utf-8"),"Pages/CI must not build Digest artifacts")
need(not (root/"scripts/build_public_digest_pdf.py").exists(),"Server-side Digest PDF generator must remain absent")
need("Новий випуск публікується тільки після фінального затвердження ADMIN_1" not in news_page and "The new issue is published only after final ADMIN_1 approval" not in news_page,"Public News/Digest UI must not expose internal ADMIN_1 workflow text")

need('finaladvice-more">Читати далі... →</span>' in js,"Every Digest Advice row must use the same visible Read-more CTA")
need("badAdvice=advice.filter" in js and 'advice-article.html?id=' in js,"Digest release gate must validate canonical Advice routes")
need('x.url!==publicUrl({content_type:x.type,slug:x.slug})' in js,"Digest release gate must validate canonical NEWS/Finance/Regulation routes")
need("ЗАВАНТАЖИТИ ДАЙДЖЕСТ PDF" in home,"Homepage must expose an explicit PDF Digest download button")
need('/\\.pdf(?:$|[?#])/i.test(d.public_url)' in public_runtime,"Public Digest binding must reject non-PDF CURRENT URLs")
need("digest-current-route-v4-20261003" in home,"Public CURRENT Digest runtime cache-busting version not advanced to FINAL_ADMIN_IIG")

if errors:
    print("STEP 26 ADMIN MASTER: FAIL")
    for e in errors: print("-",e)
    sys.exit(1)
print("STEP 26 ADMIN MASTER: 10/10 STATIC ACCEPTANCE GREEN")
print("PRE-DIGEST GENERATION GATE = READY TO GENERATE")

need("finaldigest-readmore" in js and "Читати далі... →" in js,"Every Digest news row must show explicit Read more arrow")
need('advice-article.html?id=' in js,"Digest Advice links must use canonical id route")
advice_page=(root/"advice-article.html").read_text(encoding="utf-8")
need('q.get("slug")' in advice_page and 'q.set("id",q.get("slug"))' in advice_page,"Advice page must normalize legacy slug route to id")
need("digestPdfFile" in html and "publishDigestSite" in html and "ЗАВАНТАЖИТИ PDF ДАЙДЖЕСТ НА САЙТ" in html,"Admin PDF-to-site controls missing")
need("pendingDigestPdf" in js and "new FormData()" in js and 'form.append("pdf",pendingDigestPdf' in js,"Admin must upload exact PDF binary, not rebuild on server")
need('archive_previous_current:true' in js and 'make_current:true' in js,"PDF publication must archive previous CURRENT and promote new CURRENT")
need('links_preserved!==true' in js and "PUBLIC_PDF_URL_REQUIRED" in js,"PDF publication must verify active links and PDF public URL")
