#!/usr/bin/env python3
"""Select news-draft images without approving or publishing articles.

Usage: python scripts/news_image_selector.py input.json output.json
Input is a JSON array of draft objects with `sector`, optional `news_image`
and `news_image_checks` (relevance, rights, quality, caption: booleans).
An original is used only when all four checks are explicitly true. Otherwise
select the exact same-sector repository asset. Rights evidence for internal
assets must be supplied in a separately maintained rights register; historical
manifest flags alone never certify permission. An unavailable or unauthorized
asset is flagged for review. The output is ALWAYS an unapproved draft.
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MAPPING = ROOT / 'content' / 'news-sector-image-paths.json'
MANIFEST = ROOT / 'baze_foto_news' / 'manifest.json'
CHECKS = ('relevance', 'rights', 'quality', 'caption')


def select_image(item, mapping, manifest, root=ROOT, rights=None):
    """Return an image decision, never an approval or publication decision."""
    rights = rights or {}
    sector = item.get('sector')
    paths = mapping.get('sector_images', {})
    if sector not in paths or sector not in manifest.get('sectors', {}):
        return {'image_status': 'IMAGE_REVIEW_REQUIRED', 'reason': 'UNKNOWN_SECTOR'}
    checks = item.get('news_image_checks') or {}
    original = item.get('news_image') or {}
    if isinstance(original, dict) and original.get('image_url') and all(checks.get(k) is True for k in CHECKS):
        return {'image_status': 'SELECTED', 'image_type': 'source_photo',
                'image_url': original['image_url'], 'image_credit': original.get('image_credit', ''),
                'image_source_url': original.get('image_source_url', ''), 'fallback_reason': None}
    web_path = paths[sector]
    manifest_path = manifest['sectors'][sector].get('image_url')
    if not isinstance(web_path, str) or not web_path.startswith('/') or web_path[1:] != manifest_path:
        return {'image_status': 'IMAGE_REVIEW_REQUIRED', 'reason': 'MANIFEST_PATH_MISMATCH'}
    asset = root / web_path.lstrip('/')
    if not asset.is_file():
        return {'image_status': 'IMAGE_REVIEW_REQUIRED', 'reason': 'SECTOR_ASSET_MISSING', 'image_url': web_path}
    evidence = rights.get(sector, {})
    if not isinstance(evidence, dict) or evidence.get('authorized') is not True or not evidence.get('basis'):
        return {'image_status': 'IMAGE_REVIEW_REQUIRED', 'reason': 'SECTOR_IMAGE_RIGHTS_NOT_DOCUMENTED', 'image_url': web_path}
    meta = manifest['sectors'][sector]
    return {'image_status': 'SELECTED', 'image_type': 'sector_photo', 'image_url': web_path,
            'image_rights_basis': evidence['basis'], 'image_credit': evidence.get('credit', ''),
            'image_alt': meta['image_alt'], 'image_caption': meta['image_caption'],
            'fallback_reason': 'ORIGINAL_ABSENT_OR_FAILED_FOUR_CHECKS',
            'illustrative': True, 'requires_separate_image_approval': False}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('input', type=Path)
    parser.add_argument('output', type=Path)
    parser.add_argument('--rights-register', type=Path, help='JSON map of sector to {authorized:true,basis:...,credit:...}; not generated by robot')
    args = parser.parse_args()
    mapping = json.loads(MAPPING.read_text(encoding='utf-8'))
    manifest = json.loads(MANIFEST.read_text(encoding='utf-8'))
    rights = json.loads(args.rights_register.read_text(encoding='utf-8')) if args.rights_register else {}
    drafts = json.loads(args.input.read_text(encoding='utf-8'))
    if not isinstance(drafts, list):
        parser.error('input must be a JSON array')
    output = []
    for draft in drafts:
        if not isinstance(draft, dict):
            parser.error('each draft must be an object')
        result = dict(draft)
        result['image_decision'] = select_image(draft, mapping, manifest, rights=rights)
        result['status'] = 'READY_FOR_REVIEW' if result['image_decision']['image_status'] == 'SELECTED' else 'IMAGE_REVIEW_REQUIRED'
        result['auto_publish'] = False
        result['publish_authority'] = 'ADMIN_ONLY'
        result.pop('approval', None)
        output.append(result)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(output, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    print(json.dumps({'drafts': len(output), 'image_review_required': sum(x['status'] == 'IMAGE_REVIEW_REQUIRED' for x in output), 'output': str(args.output)}, ensure_ascii=False))
    return 0


if __name__ == '__main__':
    sys.exit(main())
